excluded-events:
  - ChunkLoadEvent
  - EntitiesLoadEvent
  - EntityAddToWorldEvent
  - com.destroystokyo.paper.event.server.ServerTickEndEvent
  - com.destroystokyo.paper.event.server.ServerTickStartEvent
  - EntityMoveEvent