name: EventChecker
main: de.thelooter.eventchecker.EventChecker
version: 1.0.0
author: thelooter
api-version: 1.13
description: Prints fired events to the console

commands:
  eventchecker:
    description: Eventchecker Command
    usage: /eventchecker <option>

permissions:
  eventchecker.admin:
    description: Admin Permission
    default: op