name: Changelog
on:
  release:
    types:
      - created

jobs:
  changelog:
    runs-on: ubuntu-24.04
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@e60b5a2bd9fcd88dadf6345ff8327863fb8b490f # v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
