name: Changelog
on:
  release:
    types:
      - created

jobs:
  changelog:
    runs-on: ubuntu-24.04
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}